export const content = {
  en: {
    navLinks: [
      { id: 'hero', label: 'Home' },
      { id: 'about', label: 'About Alworya' },
      { id: 'features', label: 'Features' },
      { id: 'how', label: 'How It Works' },
      { id: 'app', label: 'App Preview' },
      { id: 'owners', label: 'For Venue Owners' },
      { id: 'testimonials', label: 'Reviews' },
      { id: 'contact', label: 'Contact' },
    ],
    heroTitle: 'Exceptional management for halls and chalets',
    heroSubtitle:
      'An integrated SaaS platform that blends luxury and efficiency to turn your business into an unforgettable experience.',
    heroCtaPrimary: 'Start now for free',
    heroCtaSecondary: 'Request a demo for venue owners',
    download: 'Download App',
    aboutTitle: 'About Alworya',
    aboutText:
      'Alworya (الوريا) is an Iraqi booking platform for wedding halls and chalets — a smart way to reserve venues across Iraq, including Baghdad and Basrah. Find spaces on the map, book instantly with OTP, and chat with owners from one elegant app.',
    featuresTitle: 'Smart Features Crafted for Premium Events',
    features: [
      'Smart search system',
      'Map-based discovery',
      'Instant booking with OTP',
      'Real-time chat with owners',
      'Favorites system',
      'Notifications system',
    ],
    howTitle: 'How It Works',
    steps: ['Search venue', 'View details', 'Book instantly', 'Verify via OTP', 'Chat & confirm deal'],
    appPreview: 'App Experience Preview',
    appCards: ['Booking Flow', 'Live Map View', 'Owner Chat'],
    ownerTitle: 'For Venue Owners',
    ownerStats: [
      { label: 'Bookings / Month', value: 280 },
      { label: 'Active Clients', value: 1200 },
      { label: 'Revenue Growth', value: 67, suffix: '%' },
    ],
    ownerItems: [
      'Manage bookings from one dashboard',
      'Chat instantly with potential clients',
      'Track analytics and revenue growth',
      'Control profile details and availability',
    ],
    testimonialsTitle: 'Trusted by Families and Venue Owners',
    testimonials: [
      {
        name: 'Sara A.',
        role: 'Bride, Baghdad',
        text: 'Alworya made our wedding planning feel premium and stress-free. We found our hall in minutes.',
      },
      {
        name: 'Noor Palace',
        role: 'Venue Owner',
        text: 'The chat and instant booking tools brought more qualified clients than any traditional ads.',
      },
      {
        name: 'Yousef H.',
        role: 'Event Planner',
        text: 'The quality of venues and verification flow creates trust for high-value event bookings.',
      },
    ],
    ctaTitle: 'Join Alworya - Where Luxury Meets Smart Booking',
    ctaSubtitle: 'Built for emotional celebrations and high-end hospitality experiences.',
    footerTagline: 'Luxury wedding experience meets smart technology platform.',
    footer: {
      legalTitle: 'Legal',
      legalLinks: [
        { label: 'Privacy Policy', href: '/privacy-policy' },
        { label: 'Terms & Conditions', href: '/terms' },
        { label: 'Delete Account', href: '/delete-account' },
      ],
      quickTitle: 'Quick Links',
      quickLinks: [
        { id: 'hero', label: 'Home' },
        { id: 'about', label: 'About Alworya' },
        { id: 'features', label: 'Features' },
        { id: 'owners', label: 'For Venue Owners' },
        { id: 'contact', label: 'Contact Us' },
      ],
      brandText: 'An advanced platform for managing halls and chalets with smart technology that elevates your business.',
      copyright: 'Copyright © 2024 Alworya - All rights reserved.',
      phone: '+964 123 456 7890',
      email: 'support@alworya.com',
    },
  },
  ar: {
    navLinks: [
      { id: 'hero', label: 'الرئيسية' },
      { id: 'about', label: 'عن الوريا' },
      { id: 'features', label: 'المزايا' },
      { id: 'how', label: 'كيف يعمل' },
      { id: 'app', label: 'استعراض التطبيق' },
      { id: 'owners', label: 'لأصحاب القاعات' },
      { id: 'testimonials', label: 'آراء العملاء' },
      { id: 'contact', label: 'تواصل معنا' },
    ],
    heroTitle: 'إدارة القاعات والشاليهات بمستوى استثنائي',
    heroSubtitle: 'نظام SaaS متكامل يجمع بين الفخامة والفعالية لتحويل أعمالك إلى تجربة لا تُنسى.',
    heroCtaPrimary: 'ابدأ الآن مجاناً',
    heroCtaSecondary: 'اطلب عرضاً لأصحاب القاعات',
    download: 'حمّل التطبيق',
    aboutTitle: 'عن الوريا',
    aboutText:
      'الوريا (Alworya) منصة حجز عراقية لقاعات الأعراس والشاليهات في عموم العراق — من بغداد إلى البصرة وأبعد. استكشف الأماكن على الخريطة، واحجز فوراً مع التحقق عبر OTP، وتواصل مباشرة مع أصحاب القاعات أو الشاليهات.',
    featuresTitle: 'مزايا ذكية مصممة للمناسبات الفاخرة',
    features: [
      'نظام بحث ذكي',
      'استكشاف عبر الخرائط',
      'حجز فوري مع OTP',
      'محادثة مباشرة مع المالك',
      'نظام المفضلة',
      'نظام الإشعارات',
    ],
    howTitle: 'كيف يعمل',
    steps: ['ابحث عن المكان', 'اطلع على التفاصيل', 'احجز فوراً', 'تحقق عبر OTP', 'دردش وأكد الاتفاق'],
    appPreview: 'معاينة تجربة التطبيق',
    appCards: ['رحلة الحجز', 'عرض الخريطة المباشر', 'محادثة المالك'],
    ownerTitle: 'لأصحاب القاعات والشاليهات',
    ownerStats: [
      { label: 'حجز شهري', value: 280 },
      { label: 'عميل نشط', value: 1200 },
      { label: 'نمو الإيراد', value: 67, suffix: '%' },
    ],
    ownerItems: [
      'إدارة الحجوزات من لوحة واحدة',
      'محادثة العملاء المحتملين مباشرة',
      'متابعة التحليلات ونمو الإيرادات',
      'إدارة الملف الشخصي والتوفر',
    ],
    testimonialsTitle: 'موثوق من العائلات وأصحاب الأماكن',
    testimonials: [
      {
        name: 'سارة',
        role: 'عروس - بغداد',
        text: 'الوريا خلّت تجربة تنظيم زفافنا راقية وسهلة جداً، ولقينا القاعة بسرعة.',
      },
      {
        name: 'قصر النور',
        role: 'صاحب قاعة',
        text: 'ميزة المحادثة والحجز الفوري جابت لنا عملاء جادين أكثر من الإعلانات التقليدية.',
      },
      {
        name: 'يوسف',
        role: 'منظم فعاليات',
        text: 'جودة الأماكن مع التحقق الفوري تعطي ثقة عالية للحجوزات الكبيرة.',
      },
    ],
    ctaTitle: 'انضم إلى الوريا - حيث الفخامة تلتقي بالحجز الذكي',
    ctaSubtitle: 'مصممة لذكريات الاحتفال المميزة وتجارب الضيافة الراقية.',
    footerTagline: 'تجربة زفاف فاخرة تلتقي مع التكنولوجيا الذكية.',
    footer: {
      legalTitle: 'قانوني',
      legalLinks: [
        { label: 'سياسة الخصوصية', href: '/privacy-policy' },
        { label: 'الشروط والأحكام', href: '/terms' },
        { label: 'حذف الحساب', href: '/delete-account' },
      ],
      quickTitle: 'الروابط السريعة',
      quickLinks: [
        { id: 'hero', label: 'الرئيسية' },
        { id: 'about', label: 'عن الوريا' },
        { id: 'features', label: 'المزايا' },
        { id: 'owners', label: 'لأصحاب القاعات' },
        { id: 'contact', label: 'تواصل معنا' },
      ],
      brandText: 'نظام أفضل لإدارة القاعات والشاليهات الفاخرة، مقدم حلول تقنية ترتقي بأعمالك.',
      copyright: 'حقوق الطبع والنشر © 2024 الوريا - جميع الحقوق محفوظة.',
      phone: '+964 123 456 7890',
      email: 'support@alworya.com',
    },
  },
}

export const routeMap = {
  hero: '/',
  about: '/about',
  features: '/features',
  how: '/how-it-works',
  app: '/app-preview',
  owners: '/owners',
  testimonials: '/testimonials',
  contact: '/contact',
}
